server.port=8080

# Gmail SMTP settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# IMPORTANT:
# Use your Gmail address here
spring.mail.username=gollaanand90143@gmail.com

# Use Gmail App Password here, NOT your normal Gmail password
spring.mail.password=ANAana901@@@

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
